# Generated by Django 5.1 on 2025-12-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='invited',
        ),
        migrations.AddField(
            model_name='profile',
            name='invited',
            field=models.CharField(blank=True, null=True),
        ),
    ]
