# Generated by Django 5.2.3 on 2025-12-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_publishrequest_remove_comment_dislikes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='about',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='years',
        ),
        migrations.AddField(
            model_name='experience',
            name='employer',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
