# Generated by Django 5.1 on 2025-12-10 18:33

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_experience_about_remove_experience_years_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=portfolio.models.Key.generate_random_code, editable=False, max_length=10, unique=True)),
                ('plan', models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='website',
            name='activation_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='activation_margin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
