# Generated by Django 5.1 on 2025-12-10 18:34

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_key_website_activation_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='code',
            field=models.CharField(blank=True, default=portfolio.models.Key.generate_random_code, editable=False, max_length=10, null=True, unique=True),
        ),
    ]
