# Generated by Django 5.1 on 2025-12-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_key_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
