# Generated by Django 5.1 on 2025-12-11 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_key_user_alter_key_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='expired',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
