# Generated by Django 5.2.3 on 2025-12-20 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_project_image_project_tech'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('payment', 'payment'), ('withdrawal', 'withdrawal')], max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.website')),
            ],
        ),
    ]
