# Generated by Django 5.2.3 on 2026-01-04 21:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='age',
        ),
        migrations.AddField(
            model_name='website',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='plan',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly'), ('Quarterly', 'Quarterly')], max_length=10),
        ),
        migrations.AlterField(
            model_name='skill',
            name='mastery',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
