# Generated by Django 5.2.3 on 2026-01-04 21:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_remove_website_age_website_birthday_alter_key_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
